//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for BookingStatus.
const (
	Confirmed BookingStatus = "confirmed"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	default:
		return false
	}
}

// Defines values for CalendarOwnerId.
const (
	OwnerDefault CalendarOwnerId = "owner-default"
)

// Valid indicates whether the value is a known member of the CalendarOwnerId enum.
func (e CalendarOwnerId) Valid() bool {
	switch e {
	case OwnerDefault:
		return true
	default:
		return false
	}
}

// Defines values for DayOfWeek.
const (
	Friday    DayOfWeek = "friday"
	Monday    DayOfWeek = "monday"
	Saturday  DayOfWeek = "saturday"
	Sunday    DayOfWeek = "sunday"
	Thursday  DayOfWeek = "thursday"
	Tuesday   DayOfWeek = "tuesday"
	Wednesday DayOfWeek = "wednesday"
)

// Valid indicates whether the value is a known member of the DayOfWeek enum.
func (e DayOfWeek) Valid() bool {
	switch e {
	case Friday:
		return true
	case Monday:
		return true
	case Saturday:
		return true
	case Sunday:
		return true
	case Thursday:
		return true
	case Tuesday:
		return true
	case Wednesday:
		return true
	default:
		return false
	}
}

// Defines values for SlotIsAvailable.
const (
	True SlotIsAvailable = true
)

// Valid indicates whether the value is a known member of the SlotIsAvailable enum.
func (e SlotIsAvailable) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	CreatedAt    time.Time     `json:"createdAt"`
	EndAt        time.Time     `json:"endAt"`
	EventTypeId  string        `json:"eventTypeId"`
	GuestComment *string       `json:"guestComment,omitempty"`
	GuestEmail   string        `json:"guestEmail"`
	GuestName    string        `json:"guestName"`
	Id           string        `json:"id"`
	OwnerSlug    string        `json:"ownerSlug"`
	StartAt      time.Time     `json:"startAt"`
	Status       BookingStatus `json:"status"`
}

// BookingStatus defines model for BookingStatus.
type BookingStatus string

// CalendarOwner defines model for CalendarOwner.
type CalendarOwner struct {
	DisplayName    string            `json:"displayName"`
	Email          string            `json:"email"`
	Id             CalendarOwnerId   `json:"id"`
	PhotoUrl       *string           `json:"photoUrl,omitempty"`
	Slug           string            `json:"slug"`
	Timezone       string            `json:"timezone"`
	WeeklySchedule []WorkDaySchedule `json:"weeklySchedule"`
}

// CalendarOwnerId defines model for CalendarOwner.Id.
type CalendarOwnerId string

// CreateBookingRequest defines model for CreateBookingRequest.
type CreateBookingRequest struct {
	EventTypeId  string    `json:"eventTypeId"`
	GuestComment *string   `json:"guestComment,omitempty"`
	GuestEmail   string    `json:"guestEmail"`
	GuestName    string    `json:"guestName"`
	SlotStartAt  time.Time `json:"slotStartAt"`
}

// CreateEventTypeRequest defines model for CreateEventTypeRequest.
type CreateEventTypeRequest struct {
	Description     *string `json:"description,omitempty"`
	DurationMinutes int32   `json:"durationMinutes"`
	Id              *string `json:"id,omitempty"`
	Name            string  `json:"name"`
}

// DayOfWeek defines model for DayOfWeek.
type DayOfWeek string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EventType defines model for EventType.
type EventType struct {
	Description     string `json:"description"`
	DurationMinutes int32  `json:"durationMinutes"`
	Id              string `json:"id"`
	Name            string `json:"name"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorResponse

// OwnerNotFoundError defines model for OwnerNotFoundError.
type OwnerNotFoundError = ErrorResponse

// OwnerProfileUpdateRequest defines model for OwnerProfileUpdateRequest.
type OwnerProfileUpdateRequest struct {
	DisplayName    string            `json:"displayName"`
	Email          string            `json:"email"`
	PhotoUrl       *string           `json:"photoUrl,omitempty"`
	Timezone       string            `json:"timezone"`
	WeeklySchedule []WorkDaySchedule `json:"weeklySchedule"`
}

// PublicOwnerProfile defines model for PublicOwnerProfile.
type PublicOwnerProfile struct {
	DisplayName    string            `json:"displayName"`
	PhotoUrl       *string           `json:"photoUrl,omitempty"`
	Slug           string            `json:"slug"`
	Timezone       string            `json:"timezone"`
	WeeklySchedule []WorkDaySchedule `json:"weeklySchedule"`
}

// Slot defines model for Slot.
type Slot struct {
	EndAt       time.Time       `json:"endAt"`
	EventTypeId string          `json:"eventTypeId"`
	IsAvailable SlotIsAvailable `json:"isAvailable"`
	StartAt     time.Time       `json:"startAt"`
}

// SlotIsAvailable defines model for Slot.IsAvailable.
type SlotIsAvailable bool

// SlotConflictError defines model for SlotConflictError.
type SlotConflictError = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// WorkDaySchedule defines model for WorkDaySchedule.
type WorkDaySchedule struct {
	DayOfWeek DayOfWeek `json:"dayOfWeek"`
	EndHour   int32     `json:"endHour"`
	IsActive  bool      `json:"isActive"`
	StartHour int32     `json:"startHour"`
}

// AdminApiListUpcomingBookingsParams defines parameters for AdminApiListUpcomingBookings.
type AdminApiListUpcomingBookingsParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// PublicApiListAvailableSlotsParams defines parameters for PublicApiListAvailableSlots.
type PublicApiListAvailableSlotsParams struct {
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To   *time.Time `form:"to,omitempty" json:"to,omitempty"`
}

// AdminApiCreateEventTypeJSONRequestBody defines body for AdminApiCreateEventType for application/json ContentType.
type AdminApiCreateEventTypeJSONRequestBody = CreateEventTypeRequest

// AdminApiUpdateOwnerJSONRequestBody defines body for AdminApiUpdateOwner for application/json ContentType.
type AdminApiUpdateOwnerJSONRequestBody = OwnerProfileUpdateRequest

// PublicApiCreateBookingJSONRequestBody defines body for PublicApiCreateBooking for application/json ContentType.
type PublicApiCreateBookingJSONRequestBody = CreateBookingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/bookings/upcoming)
	AdminApiListUpcomingBookings(w http.ResponseWriter, r *http.Request, params AdminApiListUpcomingBookingsParams)

	// (GET /admin/event-types)
	AdminApiListEventTypes(w http.ResponseWriter, r *http.Request)

	// (POST /admin/event-types)
	AdminApiCreateEventType(w http.ResponseWriter, r *http.Request)

	// (GET /admin/owner)
	AdminApiGetOwner(w http.ResponseWriter, r *http.Request)

	// (PUT /admin/owner)
	AdminApiUpdateOwner(w http.ResponseWriter, r *http.Request)

	// (GET /public/{ownerSlug})
	PublicApiGetOwnerProfile(w http.ResponseWriter, r *http.Request, ownerSlug string)

	// (POST /public/{ownerSlug}/bookings)
	PublicApiCreateBooking(w http.ResponseWriter, r *http.Request, ownerSlug string)

	// (GET /public/{ownerSlug}/event-types)
	PublicApiListPublicEventTypes(w http.ResponseWriter, r *http.Request, ownerSlug string)

	// (GET /public/{ownerSlug}/event-types/{eventTypeId}/slots)
	PublicApiListAvailableSlots(w http.ResponseWriter, r *http.Request, ownerSlug string, eventTypeId string, params PublicApiListAvailableSlotsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminApiListUpcomingBookings operation middleware
func (siw *ServerInterfaceWrapper) AdminApiListUpcomingBookings(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminApiListUpcomingBookingsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminApiListUpcomingBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminApiListEventTypes operation middleware
func (siw *ServerInterfaceWrapper) AdminApiListEventTypes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminApiListEventTypes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminApiCreateEventType operation middleware
func (siw *ServerInterfaceWrapper) AdminApiCreateEventType(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminApiCreateEventType(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminApiGetOwner operation middleware
func (siw *ServerInterfaceWrapper) AdminApiGetOwner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminApiGetOwner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminApiUpdateOwner operation middleware
func (siw *ServerInterfaceWrapper) AdminApiUpdateOwner(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminApiUpdateOwner(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublicApiGetOwnerProfile operation middleware
func (siw *ServerInterfaceWrapper) PublicApiGetOwnerProfile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ownerSlug" -------------
	var ownerSlug string

	err = runtime.BindStyledParameterWithOptions("simple", "ownerSlug", r.PathValue("ownerSlug"), &ownerSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerSlug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublicApiGetOwnerProfile(w, r, ownerSlug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublicApiCreateBooking operation middleware
func (siw *ServerInterfaceWrapper) PublicApiCreateBooking(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ownerSlug" -------------
	var ownerSlug string

	err = runtime.BindStyledParameterWithOptions("simple", "ownerSlug", r.PathValue("ownerSlug"), &ownerSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerSlug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublicApiCreateBooking(w, r, ownerSlug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublicApiListPublicEventTypes operation middleware
func (siw *ServerInterfaceWrapper) PublicApiListPublicEventTypes(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ownerSlug" -------------
	var ownerSlug string

	err = runtime.BindStyledParameterWithOptions("simple", "ownerSlug", r.PathValue("ownerSlug"), &ownerSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerSlug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublicApiListPublicEventTypes(w, r, ownerSlug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublicApiListAvailableSlots operation middleware
func (siw *ServerInterfaceWrapper) PublicApiListAvailableSlots(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ownerSlug" -------------
	var ownerSlug string

	err = runtime.BindStyledParameterWithOptions("simple", "ownerSlug", r.PathValue("ownerSlug"), &ownerSlug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerSlug", Err: err})
		return
	}

	// ------------- Path parameter "eventTypeId" -------------
	var eventTypeId string

	err = runtime.BindStyledParameterWithOptions("simple", "eventTypeId", r.PathValue("eventTypeId"), &eventTypeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "eventTypeId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PublicApiListAvailableSlotsParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublicApiListAvailableSlots(w, r, ownerSlug, eventTypeId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/admin/bookings/upcoming", wrapper.AdminApiListUpcomingBookings)
	m.HandleFunc("GET "+options.BaseURL+"/admin/event-types", wrapper.AdminApiListEventTypes)
	m.HandleFunc("POST "+options.BaseURL+"/admin/event-types", wrapper.AdminApiCreateEventType)
	m.HandleFunc("GET "+options.BaseURL+"/admin/owner", wrapper.AdminApiGetOwner)
	m.HandleFunc("PUT "+options.BaseURL+"/admin/owner", wrapper.AdminApiUpdateOwner)
	m.HandleFunc("GET "+options.BaseURL+"/public/{ownerSlug}", wrapper.PublicApiGetOwnerProfile)
	m.HandleFunc("POST "+options.BaseURL+"/public/{ownerSlug}/bookings", wrapper.PublicApiCreateBooking)
	m.HandleFunc("GET "+options.BaseURL+"/public/{ownerSlug}/event-types", wrapper.PublicApiListPublicEventTypes)
	m.HandleFunc("GET "+options.BaseURL+"/public/{ownerSlug}/event-types/{eventTypeId}/slots", wrapper.PublicApiListAvailableSlots)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXVPbOBf+Kx6976XbMG1vNncp0F1m2KRDoL3oMIywjomKLbnSETTL5L/vSI4/IxsH",
	"ErbMLlcmlo6fc57z/UAimWZSgEBNxg9ERwtIqXv8KOUtFzf2MVMyA4Uc3ItIAUVgE7T/xFKlFMmYMIrw",
	"BnkKJCS4zICMiUZlBaxCAmK743cg8HyZwQmzlzbe3xjQeCjTFAR2HzhOKU+6X09pCt633P9ReS9AzRNz",
	"432rkSrcRkeNFI2z5/8VxGRM/jeqqBiteRitSZjnh1erkCj4YbgCRsbfLNI6rqbhKkyF/euKN2xUoglr",
	"5F6WoOX1d4jQgm7CGT8QECa1SCIpYq5SYLVrla6HNAHBqJpZqJsOxbjOErrsJAQ6icypKkA4S7xhEFOT",
	"oBdItpAoL5RfmO7i1lL4lxR+cPcAt8lyHi2AmcQd4Qjpo8R+ler2iFb3ViVaqhRd+qnWOct1exXWqaHc",
	"wORj8tDxvObzDH5YZ9hk5p8NRJ1InG8XVy2rteKhJq8zFrqNdVwI6zQXAx0pniGXwqsQM4ral39yYTC/",
	"UirFBb5/VynEBcINqJ58JPxma1lA5Aq2v+zT8oguZ/FXgNt6TKVSMLq0uAzo/OkemCiecWHU+jFWPH/Q",
	"FI1aPxp32xeKx0pJdQY6k0KDp8hI5neKFLSmNwM0dxKq8z6NS0ZfBZUuBRR81uANY3cq8ZM0gjm724/R",
	"JJnFZPytP081aVpdhh08Ff4ynZ1ffZpdTI88pPsI8kF1ZeKF8M6+To/PrnaG+rOSMU/gIrM5qjtPPLng",
	"9RawX6FO7aI2fTbXCY/q9tzehK+30nuL/HYGnCfSV8x324RzPbmjPKHXST2gUBmoIF1LmQAVT2iQ+wv5",
	"RmNbB9NlkUMp4oRHuOeMMj+dnV8dzqafTk8Oz5+RT77QhDOX1vcM+Mvk9ORocn4ym14dn53Nzp6Bue3r",
	"m2Fb7zH6lKiakXx8/EMaNbTI6kmE/K4exG0/HCytnd1KVLXP1GVWWDfNY4VxEUuHi6M1TzkZBetOPJh8",
	"PiEhuQOlXedBDt4evD1w42cGgmacjMl791NIMooLZ9QRZSkXo+tchB6ZLJLpenS/ARdylgPnSzaYycSe",
	"n2T8lGu8WB9eA9BOsKIpICjtfA1+ZolzmZgmGqwOZEx+GFDLoh8Zk1jJ1BrCsTc8xocJR7m96EtLXB4C",
	"zkbvDg5y3xe4nlVoliU8ckYZfdd5m1d9ZFBqL1Ykmyl91WzRxuR8AYHK+4FgQXWgTRQBMGBv7elVWJDo",
	"Et0bK00Poq9sYS1x+9e46pifrXNIMql7tGsNXSSPRND4UbLlVpr1KdQx2q2akW+r2uqZ9h1o1u3MGJIP",
	"O4TRLjkdYDSoO1BBJE3CAiExMIKB0kgFC7AGlhkIUAZc3Fm5gV4KpD9b/i6LlVCvp/8OmO+O9shBc0n1",
	"FHc2PRrkE0GlxO49uXv+eGFnfpYhX7FDZ25sGT2UC9lVp1/nE07NsYs5Z6P4unpoK31VDusL3yar9Sq5",
	"64LYZ2bPwPYE2j/sNhSaC4RHmKfC0h7zJuHAAgVaGhVBD8tl4+XaXW9NK/lurF33zfa+qmVra/zC6aVs",
	"uv4FiWX7sKBiOWBE9AVI2H+ldfpyBwFltfttZ5RsjviPeEi0PqyDe44LBzMySoHAQCNFCGTsfsxV6ksA",
	"Q5r2MgXYrj3/p9G7/6p5/2XHglddB2puMHqobaxWI51IHOga5R5r7u7szzFCr6zmom0raf/tCfpS08tH",
	"xmsqBe7v7wAAAP//hr24fI0iAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
