package service

import (
	"testing"
	"time"

	"github.com/alexmented/ai-for-developers-project-386/backend/internal/api"
)

func TestListAvailableSlots_DefaultWindowAndWorkingHours(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	slots, err := svc.ListAvailableSlots("name-owner", "meeting-15", nil, nil)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if len(slots) == 0 {
		t.Fatalf("expected non-empty slots")
	}

	first := slots[0]
	if !first.StartAt.Equal(now) {
		t.Fatalf("expected first slot to start at %s, got %s", now, first.StartAt)
	}

	if !bool(first.IsAvailable) {
		t.Fatalf("expected first slot to be available")
	}
}

func TestCreateBooking_RejectsConflictsAcrossEventTypes(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	_, err := svc.CreateBooking("name-owner", CreateBookingInput{
		EventTypeID: "meeting-15",
		SlotStartAt: now,
		GuestName:   "Ivan",
		GuestEmail:  "ivan@example.com",
	})
	if err != nil {
		t.Fatalf("expected first booking success, got %v", err)
	}

	_, err = svc.CreateBooking("name-owner", CreateBookingInput{
		EventTypeID: "meeting-30",
		SlotStartAt: now,
		GuestName:   "Petr",
		GuestEmail:  "petr@example.com",
	})
	if err == nil {
		t.Fatalf("expected slot conflict error")
	}

	svcErr, ok := err.(*ServiceError)
	if !ok {
		t.Fatalf("expected ServiceError, got %T", err)
	}

	if svcErr.Code != "SLOT_CONFLICT" {
		t.Fatalf("expected SLOT_CONFLICT, got %s", svcErr.Code)
	}
}

func TestCreateEventType_StoresAndReturnsNewEventType(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	explicitID := "meeting-45"

	created, err := svc.CreateEventType(CreateEventTypeInput{
		ID:              &explicitID,
		Name:            "Встреча 45 минут",
		Description:     "Расширенная встреча",
		DurationMinutes: 45,
	})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if created.Id != "meeting-45" {
		t.Fatalf("expected id meeting-45, got %s", created.Id)
	}

	types, err := svc.ListEventTypes("name-owner")
	if err != nil {
		t.Fatalf("expected no error on list, got %v", err)
	}

	found := false
	for _, eventType := range types {
		if eventType.Id == "meeting-45" {
			found = true
			break
		}
	}

	if !found {
		t.Fatalf("expected created event type in list")
	}
}

func TestCreateEventType_GeneratesIDWhenMissing(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	created, err := svc.CreateEventType(CreateEventTypeInput{
		Name:            "Demo Event",
		Description:     "autogenerated id",
		DurationMinutes: 25,
	})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if created.Id == "" {
		t.Fatalf("expected generated id")
	}
}

func TestUpdateOwnerProfile_UpdatesFieldsAndAffectsSlots(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	photoURL := "https://example.com/avatar.jpg"
	owner, err := svc.UpdateOwnerProfile(UpdateOwnerProfileInput{
		PhotoURL:    &photoURL,
		DisplayName: "Alex",
		Email:       "alex@example.com",
		Timezone:    "UTC",
		WeeklySchedule: []api.WorkDaySchedule{
			{DayOfWeek: api.Monday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Tuesday, IsActive: true, StartHour: 11, EndHour: 13},
			{DayOfWeek: api.Wednesday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Thursday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Friday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Saturday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Sunday, IsActive: true, StartHour: 9, EndHour: 18},
		},
	})
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if owner.DisplayName != "Alex" {
		t.Fatalf("expected displayName Alex, got %s", owner.DisplayName)
	}
	if owner.Email != "alex@example.com" {
		t.Fatalf("expected email alex@example.com, got %s", owner.Email)
	}
	if owner.PhotoUrl == nil || *owner.PhotoUrl != photoURL {
		t.Fatalf("expected photoUrl %s", photoURL)
	}
	tuesday, ok := scheduleForWeekday(owner.WeeklySchedule, time.Tuesday)
	if !ok {
		t.Fatalf("expected tuesday schedule")
	}
	if tuesday.StartHour != 11 || tuesday.EndHour != 13 {
		t.Fatalf("expected tuesday hours 11-13, got %d-%d", tuesday.StartHour, tuesday.EndHour)
	}

	slots, err := svc.ListAvailableSlots("name-owner", "meeting-15", nil, nil)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}
	if len(slots) == 0 {
		t.Fatalf("expected slots")
	}

	first := slots[0]
	if first.StartAt.Hour() != 11 {
		t.Fatalf("expected first slot at 11:00 UTC, got %s", first.StartAt.Format(time.RFC3339))
	}
}

func TestBookingDoesNotBlockPrecedingSlot(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	// Book the 9:30-10:00 slot (30-min event)
	bookedStart := time.Date(2026, 3, 31, 6, 30, 0, 0, time.UTC)
	_, err := svc.CreateBooking("name-owner", CreateBookingInput{
		EventTypeID: "meeting-30",
		SlotStartAt: bookedStart,
		GuestName:   "Ivan",
		GuestEmail:  "ivan@example.com",
	})
	if err != nil {
		t.Fatalf("expected booking success, got %v", err)
	}

	slots, err := svc.ListAvailableSlots("name-owner", "meeting-30", nil, nil)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	// The 9:00-9:30 slot (preceding) must still be available
	for _, slot := range slots {
		if slot.StartAt.Equal(time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)) {
			if !bool(slot.IsAvailable) {
				t.Fatalf("expected preceding slot 9:00-9:30 to be available, but it was blocked")
			}
		}
		if slot.StartAt.Equal(bookedStart) {
			if bool(slot.IsAvailable) {
				t.Fatalf("expected booked slot 9:30-10:00 to be unavailable")
			}
		}
	}
}

func TestUpdateOwnerProfile_RejectsInvalidHours(t *testing.T) {
	now := time.Date(2026, 3, 31, 6, 0, 0, 0, time.UTC)
	svc := NewCalendarService(func() time.Time { return now })

	_, err := svc.UpdateOwnerProfile(UpdateOwnerProfileInput{
		DisplayName: "Alex",
		Email:       "alex@example.com",
		Timezone:    "UTC",
		WeeklySchedule: []api.WorkDaySchedule{
			{DayOfWeek: api.Monday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Tuesday, IsActive: true, StartHour: 18, EndHour: 9},
			{DayOfWeek: api.Wednesday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Thursday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Friday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Saturday, IsActive: true, StartHour: 9, EndHour: 18},
			{DayOfWeek: api.Sunday, IsActive: true, StartHour: 9, EndHour: 18},
		},
	})
	if err == nil {
		t.Fatalf("expected validation error")
	}

	svcErr, ok := err.(*ServiceError)
	if !ok {
		t.Fatalf("expected ServiceError, got %T", err)
	}

	if svcErr.Code != "VALIDATION_ERROR" {
		t.Fatalf("expected VALIDATION_ERROR, got %s", svcErr.Code)
	}
}
